version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
  
  build:
    commands:
      - |
        echo "Starting Lambda deployment..."
        
        # Deploy ALL functions in the repository
        for dir in functions/*/; do
          FUNC_NAME=$(basename "$dir")
          PY_FILE="functions/${FUNC_NAME}/${FUNC_NAME}.py"
          
          if [ -f "$PY_FILE" ]; then
            echo ""
            echo "========================================="
            echo "📦 Deploying: $FUNC_NAME"
            echo "========================================="
            
            PACKAGE_DIR=$(mktemp -d)
            cd "functions/${FUNC_NAME}"
            
            if [ -f "requirements.txt" ]; then
              echo "📚 Installing dependencies..."
              pip install -r requirements.txt -t "$PACKAGE_DIR" --quiet
              rm -rf "$PACKAGE_DIR/boto3"* "$PACKAGE_DIR/botocore"* "$PACKAGE_DIR/s3transfer"* "$PACKAGE_DIR/jmespath"*
            fi
            
            echo "📄 Copying Python files..."
            cp *.py "$PACKAGE_DIR/"
            
            cd "$PACKAGE_DIR"
            zip -r -q "/tmp/${FUNC_NAME}.zip" .
            
            echo "🚀 Updating Lambda function: $FUNC_NAME"
            aws lambda update-function-code \
              --function-name "$FUNC_NAME" \
              --zip-file "fileb:///tmp/${FUNC_NAME}.zip" \
              --region us-east-2
            
            if [ $? -eq 0 ]; then
              echo "✅ Successfully deployed $FUNC_NAME"
            else
              echo "❌ Failed to deploy $FUNC_NAME"
              exit 1
            fi
            
            rm -rf "$PACKAGE_DIR"
            cd "$CODEBUILD_SRC_DIR"
          else
            echo "⚠️  Warning: $PY_FILE not found, skipping $FUNC_NAME"
          fi
        done
        
        echo ""
        echo "========================================="
        echo "✅ Deployment completed successfully!"
        echo "========================================="

artifacts:
  files:
    - '**/*'